[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"
      NETLIFY_EXCLUDE_RENDERING = "true"
    NETLIFY_EXCLUDE_EXTERNAL_REQUESTS = "true"

[build]
  command = "OUTPUT=netlify astro build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

